# Generated by Django 5.2.6 on 2025-09-15 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cycle_hours_used', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LogSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('start_location', models.CharField(max_length=255)),
                ('end_location', models.CharField(blank=True, max_length=255, null=True)),
                ('total_hours', models.FloatField(default=0)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logsheets', to='logs.driver')),
            ],
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('activity_type', models.CharField(choices=[('driving', 'Driving'), ('on_duty', 'On Duty'), ('off_duty', 'Off Duty'), ('rest', 'Rest')], max_length=20)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('logsheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='logs.logsheet')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('type', models.CharField(choices=[('rest', 'Rest'), ('fuel', 'Fuel'), ('pickup', 'Pickup'), ('dropoff', 'Dropoff')], max_length=20)),
                ('duration_hours', models.FloatField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('logsheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='logs.logsheet')),
            ],
        ),
    ]
