# Generated by Django 5.2.6 on 2025-09-16 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logentry',
            options={'ordering': ['day', 'start_hour']},
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='logentry',
            name='day',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='logentry',
            name='end_hour',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='logentry',
            name='start_hour',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='activity_type',
            field=models.CharField(choices=[('driving', 'Driving'), ('on_duty', 'On Duty'), ('off_duty', 'Off Duty'), ('rest', 'Rest'), ('sleeper', 'Sleeper')], max_length=20),
        ),
    ]
